// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as PublicSchema } from './public/PublicSchema';
import type { default as Zero0Schema } from './zero_0/Zero0Schema';
import type { default as ZeroSchema } from './zero/ZeroSchema';

type Database = PublicSchema & Zero0Schema & ZeroSchema;

export default Database;
