// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.collection */
export type CollectionId = string & { __brand: 'CollectionId' };

/** Represents the table public.collection */
export default interface CollectionTable {
  id: ColumnType<CollectionId, CollectionId, CollectionId>;

  ownerId: ColumnType<UserId | null, UserId | null, UserId | null>;

  name: ColumnType<string, string, string>;
}

export type Collection = Selectable<CollectionTable>;

export type NewCollection = Insertable<CollectionTable>;

export type CollectionUpdate = Updateable<CollectionTable>;
