// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as UserTable } from './User';
import type { default as CollectionTable } from './Collection';
import type { default as ResourceTable } from './Resource';

export default interface PublicSchema {
  user: UserTable;

  collection: CollectionTable;

  resource: ResourceTable;
}
