// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for zero.schemaVersions */
export type SchemaVersionsLock = boolean & { __brand: 'SchemaVersionsLock' };

/** Represents the table zero.schemaVersions */
export default interface SchemaVersionsTable {
  lock: ColumnType<SchemaVersionsLock, SchemaVersionsLock | undefined, SchemaVersionsLock>;

  minSupportedVersion: ColumnType<number | null, number | null, number | null>;

  maxSupportedVersion: ColumnType<number | null, number | null, number | null>;
}

export type SchemaVersions = Selectable<SchemaVersionsTable>;

export type NewSchemaVersions = Insertable<SchemaVersionsTable>;

export type SchemaVersionsUpdate = Updateable<SchemaVersionsTable>;
