// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as SchemaVersionsTable } from './SchemaVersions';

export default interface ZeroSchema {
  schemaVersions: SchemaVersionsTable;
}
