// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for zero_0.clients */
export type ClientsClientGroupID = string & { __brand: 'ClientsClientGroupID' };

/** Identifier type for zero_0.clients */
export type ClientsClientID = string & { __brand: 'ClientsClientID' };

/** Represents the table zero_0.clients */
export default interface ClientsTable {
  clientGroupID: ColumnType<ClientsClientGroupID, ClientsClientGroupID, ClientsClientGroupID>;

  clientID: ColumnType<ClientsClientID, ClientsClientID, ClientsClientID>;

  lastMutationID: ColumnType<string, string, string>;

  userID: ColumnType<string | null, string | null, string | null>;
}

export type Clients = Selectable<ClientsTable>;

export type NewClients = Insertable<ClientsTable>;

export type ClientsUpdate = Updateable<ClientsTable>;
