// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for zero_0.shardConfig */
export type ShardConfigLock = boolean & { __brand: 'ShardConfigLock' };

/** Represents the table zero_0.shardConfig */
export default interface ShardConfigTable {
  lock: ColumnType<ShardConfigLock, ShardConfigLock | undefined, ShardConfigLock>;

  publications: ColumnType<string[], string[], string[]>;

  ddlDetection: ColumnType<boolean, boolean, boolean>;

  initialSchema: ColumnType<unknown | null, unknown | null, unknown | null>;
}

export type ShardConfig = Selectable<ShardConfigTable>;

export type NewShardConfig = Insertable<ShardConfigTable>;

export type ShardConfigUpdate = Updateable<ShardConfigTable>;
