// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as VersionHistoryTable } from './VersionHistory';
import type { default as ClientsTable } from './Clients';
import type { default as ShardConfigTable } from './ShardConfig';

export default interface Zero0Schema {
  versionHistory: VersionHistoryTable;

  clients: ClientsTable;

  shardConfig: ShardConfigTable;
}
